// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ov5640_otsu_threshold.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int ov5640_otsu_threshold::C_S_AXI_DATA_WIDTH = "100000";
const int ov5640_otsu_threshold::C_S_AXI_WSTRB_WIDTH = "100";
const int ov5640_otsu_threshold::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic ov5640_otsu_threshold::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<24> ov5640_otsu_threshold::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<3> ov5640_otsu_threshold::ap_const_lv3_0 = "000";
const sc_lv<1> ov5640_otsu_threshold::ap_const_lv1_0 = "0";
const sc_logic ov5640_otsu_threshold::ap_const_logic_0 = sc_dt::Log_0;

ov5640_otsu_threshold::ov5640_otsu_threshold(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ov5640_otsu_threshold_AXILiteS_s_axi_U = new ov5640_otsu_threshold_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("ov5640_otsu_threshold_AXILiteS_s_axi_U");
    ov5640_otsu_threshold_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->ACLK(ap_clk);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->rows(rows);
    ov5640_otsu_threshold_AXILiteS_s_axi_U->cols(cols);
    Block_Mat_exit49_pro_U0 = new Block_Mat_exit49_pro("Block_Mat_exit49_pro_U0");
    Block_Mat_exit49_pro_U0->ap_clk(ap_clk);
    Block_Mat_exit49_pro_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit49_pro_U0->ap_start(Block_Mat_exit49_pro_U0_ap_start);
    Block_Mat_exit49_pro_U0->start_full_n(Block_Mat_exit49_pro_U0_start_full_n);
    Block_Mat_exit49_pro_U0->ap_done(Block_Mat_exit49_pro_U0_ap_done);
    Block_Mat_exit49_pro_U0->ap_continue(Block_Mat_exit49_pro_U0_ap_continue);
    Block_Mat_exit49_pro_U0->ap_idle(Block_Mat_exit49_pro_U0_ap_idle);
    Block_Mat_exit49_pro_U0->ap_ready(Block_Mat_exit49_pro_U0_ap_ready);
    Block_Mat_exit49_pro_U0->start_out(Block_Mat_exit49_pro_U0_start_out);
    Block_Mat_exit49_pro_U0->start_write(Block_Mat_exit49_pro_U0_start_write);
    Block_Mat_exit49_pro_U0->rows(rows);
    Block_Mat_exit49_pro_U0->cols(cols);
    Block_Mat_exit49_pro_U0->img_0_rows_V_out_din(Block_Mat_exit49_pro_U0_img_0_rows_V_out_din);
    Block_Mat_exit49_pro_U0->img_0_rows_V_out_full_n(img_0_rows_V_c_full_n);
    Block_Mat_exit49_pro_U0->img_0_rows_V_out_write(Block_Mat_exit49_pro_U0_img_0_rows_V_out_write);
    Block_Mat_exit49_pro_U0->img_0_cols_V_out_din(Block_Mat_exit49_pro_U0_img_0_cols_V_out_din);
    Block_Mat_exit49_pro_U0->img_0_cols_V_out_full_n(img_0_cols_V_c_full_n);
    Block_Mat_exit49_pro_U0->img_0_cols_V_out_write(Block_Mat_exit49_pro_U0_img_0_cols_V_out_write);
    Block_Mat_exit49_pro_U0->img_1_rows_V_out_din(Block_Mat_exit49_pro_U0_img_1_rows_V_out_din);
    Block_Mat_exit49_pro_U0->img_1_rows_V_out_full_n(img_1_rows_V_c_full_n);
    Block_Mat_exit49_pro_U0->img_1_rows_V_out_write(Block_Mat_exit49_pro_U0_img_1_rows_V_out_write);
    Block_Mat_exit49_pro_U0->img_1_cols_V_out_din(Block_Mat_exit49_pro_U0_img_1_cols_V_out_din);
    Block_Mat_exit49_pro_U0->img_1_cols_V_out_full_n(img_1_cols_V_c_full_n);
    Block_Mat_exit49_pro_U0->img_1_cols_V_out_write(Block_Mat_exit49_pro_U0_img_1_cols_V_out_write);
    Block_Mat_exit49_pro_U0->img_2_rows_V_out_din(Block_Mat_exit49_pro_U0_img_2_rows_V_out_din);
    Block_Mat_exit49_pro_U0->img_2_rows_V_out_full_n(img_2_rows_V_c_full_n);
    Block_Mat_exit49_pro_U0->img_2_rows_V_out_write(Block_Mat_exit49_pro_U0_img_2_rows_V_out_write);
    Block_Mat_exit49_pro_U0->img_2_cols_V_out_din(Block_Mat_exit49_pro_U0_img_2_cols_V_out_din);
    Block_Mat_exit49_pro_U0->img_2_cols_V_out_full_n(img_2_cols_V_c_full_n);
    Block_Mat_exit49_pro_U0->img_2_cols_V_out_write(Block_Mat_exit49_pro_U0_img_2_cols_V_out_write);
    Block_Mat_exit49_pro_U0->img_3_rows_V_out_din(Block_Mat_exit49_pro_U0_img_3_rows_V_out_din);
    Block_Mat_exit49_pro_U0->img_3_rows_V_out_full_n(img_3_rows_V_c_full_n);
    Block_Mat_exit49_pro_U0->img_3_rows_V_out_write(Block_Mat_exit49_pro_U0_img_3_rows_V_out_write);
    Block_Mat_exit49_pro_U0->img_3_cols_V_out_din(Block_Mat_exit49_pro_U0_img_3_cols_V_out_din);
    Block_Mat_exit49_pro_U0->img_3_cols_V_out_full_n(img_3_cols_V_c_full_n);
    Block_Mat_exit49_pro_U0->img_3_cols_V_out_write(Block_Mat_exit49_pro_U0_img_3_cols_V_out_write);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->start_full_n(start_for_CvtColor_U0_full_n);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->start_out(AXIvideo2Mat_U0_start_out);
    AXIvideo2Mat_U0->start_write(AXIvideo2Mat_U0_start_write);
    AXIvideo2Mat_U0->INPUT_STREAM_TDATA(INPUT_STREAM_TDATA);
    AXIvideo2Mat_U0->INPUT_STREAM_TVALID(INPUT_STREAM_TVALID);
    AXIvideo2Mat_U0->INPUT_STREAM_TREADY(AXIvideo2Mat_U0_INPUT_STREAM_TREADY);
    AXIvideo2Mat_U0->INPUT_STREAM_TKEEP(INPUT_STREAM_TKEEP);
    AXIvideo2Mat_U0->INPUT_STREAM_TSTRB(INPUT_STREAM_TSTRB);
    AXIvideo2Mat_U0->INPUT_STREAM_TUSER(INPUT_STREAM_TUSER);
    AXIvideo2Mat_U0->INPUT_STREAM_TLAST(INPUT_STREAM_TLAST);
    AXIvideo2Mat_U0->INPUT_STREAM_TID(INPUT_STREAM_TID);
    AXIvideo2Mat_U0->INPUT_STREAM_TDEST(INPUT_STREAM_TDEST);
    AXIvideo2Mat_U0->img_rows_V_dout(img_0_rows_V_c_dout);
    AXIvideo2Mat_U0->img_rows_V_empty_n(img_0_rows_V_c_empty_n);
    AXIvideo2Mat_U0->img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read);
    AXIvideo2Mat_U0->img_cols_V_dout(img_0_cols_V_c_dout);
    AXIvideo2Mat_U0->img_cols_V_empty_n(img_0_cols_V_c_empty_n);
    AXIvideo2Mat_U0->img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read);
    AXIvideo2Mat_U0->img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    AXIvideo2Mat_U0->img_data_stream_0_V_full_n(img_0_data_stream_0_full_n);
    AXIvideo2Mat_U0->img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    AXIvideo2Mat_U0->img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    AXIvideo2Mat_U0->img_data_stream_1_V_full_n(img_0_data_stream_1_full_n);
    AXIvideo2Mat_U0->img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    AXIvideo2Mat_U0->img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    AXIvideo2Mat_U0->img_data_stream_2_V_full_n(img_0_data_stream_2_full_n);
    AXIvideo2Mat_U0->img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    AXIvideo2Mat_U0->img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    AXIvideo2Mat_U0->img_rows_V_out_full_n(img_0_rows_V_c22_full_n);
    AXIvideo2Mat_U0->img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    AXIvideo2Mat_U0->img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    AXIvideo2Mat_U0->img_cols_V_out_full_n(img_0_cols_V_c23_full_n);
    AXIvideo2Mat_U0->img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    CvtColor_U0 = new CvtColor("CvtColor_U0");
    CvtColor_U0->ap_clk(ap_clk);
    CvtColor_U0->ap_rst(ap_rst_n_inv);
    CvtColor_U0->ap_start(CvtColor_U0_ap_start);
    CvtColor_U0->ap_done(CvtColor_U0_ap_done);
    CvtColor_U0->ap_continue(CvtColor_U0_ap_continue);
    CvtColor_U0->ap_idle(CvtColor_U0_ap_idle);
    CvtColor_U0->ap_ready(CvtColor_U0_ap_ready);
    CvtColor_U0->p_src_rows_V_dout(img_0_rows_V_c22_dout);
    CvtColor_U0->p_src_rows_V_empty_n(img_0_rows_V_c22_empty_n);
    CvtColor_U0->p_src_rows_V_read(CvtColor_U0_p_src_rows_V_read);
    CvtColor_U0->p_src_cols_V_dout(img_0_cols_V_c23_dout);
    CvtColor_U0->p_src_cols_V_empty_n(img_0_cols_V_c23_empty_n);
    CvtColor_U0->p_src_cols_V_read(CvtColor_U0_p_src_cols_V_read);
    CvtColor_U0->p_src_data_stream_0_V_dout(img_0_data_stream_0_dout);
    CvtColor_U0->p_src_data_stream_0_V_empty_n(img_0_data_stream_0_empty_n);
    CvtColor_U0->p_src_data_stream_0_V_read(CvtColor_U0_p_src_data_stream_0_V_read);
    CvtColor_U0->p_src_data_stream_1_V_dout(img_0_data_stream_1_dout);
    CvtColor_U0->p_src_data_stream_1_V_empty_n(img_0_data_stream_1_empty_n);
    CvtColor_U0->p_src_data_stream_1_V_read(CvtColor_U0_p_src_data_stream_1_V_read);
    CvtColor_U0->p_src_data_stream_2_V_dout(img_0_data_stream_2_dout);
    CvtColor_U0->p_src_data_stream_2_V_empty_n(img_0_data_stream_2_empty_n);
    CvtColor_U0->p_src_data_stream_2_V_read(CvtColor_U0_p_src_data_stream_2_V_read);
    CvtColor_U0->p_dst_data_stream_V_din(CvtColor_U0_p_dst_data_stream_V_din);
    CvtColor_U0->p_dst_data_stream_V_full_n(img_1_data_stream_0_full_n);
    CvtColor_U0->p_dst_data_stream_V_write(CvtColor_U0_p_dst_data_stream_V_write);
    Threshold_U0 = new Threshold("Threshold_U0");
    Threshold_U0->ap_clk(ap_clk);
    Threshold_U0->ap_rst(ap_rst_n_inv);
    Threshold_U0->ap_start(Threshold_U0_ap_start);
    Threshold_U0->ap_done(Threshold_U0_ap_done);
    Threshold_U0->ap_continue(Threshold_U0_ap_continue);
    Threshold_U0->ap_idle(Threshold_U0_ap_idle);
    Threshold_U0->ap_ready(Threshold_U0_ap_ready);
    Threshold_U0->p_src_rows_V_dout(img_1_rows_V_c_dout);
    Threshold_U0->p_src_rows_V_empty_n(img_1_rows_V_c_empty_n);
    Threshold_U0->p_src_rows_V_read(Threshold_U0_p_src_rows_V_read);
    Threshold_U0->p_src_cols_V_dout(img_1_cols_V_c_dout);
    Threshold_U0->p_src_cols_V_empty_n(img_1_cols_V_c_empty_n);
    Threshold_U0->p_src_cols_V_read(Threshold_U0_p_src_cols_V_read);
    Threshold_U0->p_src_data_stream_V_dout(img_1_data_stream_0_dout);
    Threshold_U0->p_src_data_stream_V_empty_n(img_1_data_stream_0_empty_n);
    Threshold_U0->p_src_data_stream_V_read(Threshold_U0_p_src_data_stream_V_read);
    Threshold_U0->p_dst_data_stream_V_din(Threshold_U0_p_dst_data_stream_V_din);
    Threshold_U0->p_dst_data_stream_V_full_n(img_2_data_stream_0_full_n);
    Threshold_U0->p_dst_data_stream_V_write(Threshold_U0_p_dst_data_stream_V_write);
    CvtColor_1_U0 = new CvtColor_1("CvtColor_1_U0");
    CvtColor_1_U0->ap_clk(ap_clk);
    CvtColor_1_U0->ap_rst(ap_rst_n_inv);
    CvtColor_1_U0->ap_start(CvtColor_1_U0_ap_start);
    CvtColor_1_U0->ap_done(CvtColor_1_U0_ap_done);
    CvtColor_1_U0->ap_continue(CvtColor_1_U0_ap_continue);
    CvtColor_1_U0->ap_idle(CvtColor_1_U0_ap_idle);
    CvtColor_1_U0->ap_ready(CvtColor_1_U0_ap_ready);
    CvtColor_1_U0->p_src_rows_V_dout(img_2_rows_V_c_dout);
    CvtColor_1_U0->p_src_rows_V_empty_n(img_2_rows_V_c_empty_n);
    CvtColor_1_U0->p_src_rows_V_read(CvtColor_1_U0_p_src_rows_V_read);
    CvtColor_1_U0->p_src_cols_V_dout(img_2_cols_V_c_dout);
    CvtColor_1_U0->p_src_cols_V_empty_n(img_2_cols_V_c_empty_n);
    CvtColor_1_U0->p_src_cols_V_read(CvtColor_1_U0_p_src_cols_V_read);
    CvtColor_1_U0->p_src_data_stream_V_dout(img_2_data_stream_0_dout);
    CvtColor_1_U0->p_src_data_stream_V_empty_n(img_2_data_stream_0_empty_n);
    CvtColor_1_U0->p_src_data_stream_V_read(CvtColor_1_U0_p_src_data_stream_V_read);
    CvtColor_1_U0->p_dst_data_stream_0_V_din(CvtColor_1_U0_p_dst_data_stream_0_V_din);
    CvtColor_1_U0->p_dst_data_stream_0_V_full_n(img_3_data_stream_0_full_n);
    CvtColor_1_U0->p_dst_data_stream_0_V_write(CvtColor_1_U0_p_dst_data_stream_0_V_write);
    CvtColor_1_U0->p_dst_data_stream_1_V_din(CvtColor_1_U0_p_dst_data_stream_1_V_din);
    CvtColor_1_U0->p_dst_data_stream_1_V_full_n(img_3_data_stream_1_full_n);
    CvtColor_1_U0->p_dst_data_stream_1_V_write(CvtColor_1_U0_p_dst_data_stream_1_V_write);
    CvtColor_1_U0->p_dst_data_stream_2_V_din(CvtColor_1_U0_p_dst_data_stream_2_V_din);
    CvtColor_1_U0->p_dst_data_stream_2_V_full_n(img_3_data_stream_2_full_n);
    CvtColor_1_U0->p_dst_data_stream_2_V_write(CvtColor_1_U0_p_dst_data_stream_2_V_write);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_rows_V_dout(img_3_rows_V_c_dout);
    Mat2AXIvideo_U0->img_rows_V_empty_n(img_3_rows_V_c_empty_n);
    Mat2AXIvideo_U0->img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read);
    Mat2AXIvideo_U0->img_cols_V_dout(img_3_cols_V_c_dout);
    Mat2AXIvideo_U0->img_cols_V_empty_n(img_3_cols_V_c_empty_n);
    Mat2AXIvideo_U0->img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read);
    Mat2AXIvideo_U0->img_data_stream_0_V_dout(img_3_data_stream_0_dout);
    Mat2AXIvideo_U0->img_data_stream_0_V_empty_n(img_3_data_stream_0_empty_n);
    Mat2AXIvideo_U0->img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    Mat2AXIvideo_U0->img_data_stream_1_V_dout(img_3_data_stream_1_dout);
    Mat2AXIvideo_U0->img_data_stream_1_V_empty_n(img_3_data_stream_1_empty_n);
    Mat2AXIvideo_U0->img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    Mat2AXIvideo_U0->img_data_stream_2_V_dout(img_3_data_stream_2_dout);
    Mat2AXIvideo_U0->img_data_stream_2_V_empty_n(img_3_data_stream_2_empty_n);
    Mat2AXIvideo_U0->img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TDATA(Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TVALID(Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TREADY(OUTPUT_STREAM_TREADY);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TKEEP(Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TSTRB(Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TUSER(Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TLAST(Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TID(Mat2AXIvideo_U0_OUTPUT_STREAM_TID);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TDEST(Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST);
    img_0_rows_V_c_U = new fifo_w32_d2_A("img_0_rows_V_c_U");
    img_0_rows_V_c_U->clk(ap_clk);
    img_0_rows_V_c_U->reset(ap_rst_n_inv);
    img_0_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_c_U->if_din(Block_Mat_exit49_pro_U0_img_0_rows_V_out_din);
    img_0_rows_V_c_U->if_full_n(img_0_rows_V_c_full_n);
    img_0_rows_V_c_U->if_write(Block_Mat_exit49_pro_U0_img_0_rows_V_out_write);
    img_0_rows_V_c_U->if_dout(img_0_rows_V_c_dout);
    img_0_rows_V_c_U->if_empty_n(img_0_rows_V_c_empty_n);
    img_0_rows_V_c_U->if_read(AXIvideo2Mat_U0_img_rows_V_read);
    img_0_cols_V_c_U = new fifo_w32_d2_A("img_0_cols_V_c_U");
    img_0_cols_V_c_U->clk(ap_clk);
    img_0_cols_V_c_U->reset(ap_rst_n_inv);
    img_0_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_c_U->if_din(Block_Mat_exit49_pro_U0_img_0_cols_V_out_din);
    img_0_cols_V_c_U->if_full_n(img_0_cols_V_c_full_n);
    img_0_cols_V_c_U->if_write(Block_Mat_exit49_pro_U0_img_0_cols_V_out_write);
    img_0_cols_V_c_U->if_dout(img_0_cols_V_c_dout);
    img_0_cols_V_c_U->if_empty_n(img_0_cols_V_c_empty_n);
    img_0_cols_V_c_U->if_read(AXIvideo2Mat_U0_img_cols_V_read);
    img_1_rows_V_c_U = new fifo_w32_d4_A("img_1_rows_V_c_U");
    img_1_rows_V_c_U->clk(ap_clk);
    img_1_rows_V_c_U->reset(ap_rst_n_inv);
    img_1_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_din(Block_Mat_exit49_pro_U0_img_1_rows_V_out_din);
    img_1_rows_V_c_U->if_full_n(img_1_rows_V_c_full_n);
    img_1_rows_V_c_U->if_write(Block_Mat_exit49_pro_U0_img_1_rows_V_out_write);
    img_1_rows_V_c_U->if_dout(img_1_rows_V_c_dout);
    img_1_rows_V_c_U->if_empty_n(img_1_rows_V_c_empty_n);
    img_1_rows_V_c_U->if_read(Threshold_U0_p_src_rows_V_read);
    img_1_cols_V_c_U = new fifo_w32_d4_A("img_1_cols_V_c_U");
    img_1_cols_V_c_U->clk(ap_clk);
    img_1_cols_V_c_U->reset(ap_rst_n_inv);
    img_1_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_din(Block_Mat_exit49_pro_U0_img_1_cols_V_out_din);
    img_1_cols_V_c_U->if_full_n(img_1_cols_V_c_full_n);
    img_1_cols_V_c_U->if_write(Block_Mat_exit49_pro_U0_img_1_cols_V_out_write);
    img_1_cols_V_c_U->if_dout(img_1_cols_V_c_dout);
    img_1_cols_V_c_U->if_empty_n(img_1_cols_V_c_empty_n);
    img_1_cols_V_c_U->if_read(Threshold_U0_p_src_cols_V_read);
    img_2_rows_V_c_U = new fifo_w32_d5_A("img_2_rows_V_c_U");
    img_2_rows_V_c_U->clk(ap_clk);
    img_2_rows_V_c_U->reset(ap_rst_n_inv);
    img_2_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_2_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_2_rows_V_c_U->if_din(Block_Mat_exit49_pro_U0_img_2_rows_V_out_din);
    img_2_rows_V_c_U->if_full_n(img_2_rows_V_c_full_n);
    img_2_rows_V_c_U->if_write(Block_Mat_exit49_pro_U0_img_2_rows_V_out_write);
    img_2_rows_V_c_U->if_dout(img_2_rows_V_c_dout);
    img_2_rows_V_c_U->if_empty_n(img_2_rows_V_c_empty_n);
    img_2_rows_V_c_U->if_read(CvtColor_1_U0_p_src_rows_V_read);
    img_2_cols_V_c_U = new fifo_w32_d5_A("img_2_cols_V_c_U");
    img_2_cols_V_c_U->clk(ap_clk);
    img_2_cols_V_c_U->reset(ap_rst_n_inv);
    img_2_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_2_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_2_cols_V_c_U->if_din(Block_Mat_exit49_pro_U0_img_2_cols_V_out_din);
    img_2_cols_V_c_U->if_full_n(img_2_cols_V_c_full_n);
    img_2_cols_V_c_U->if_write(Block_Mat_exit49_pro_U0_img_2_cols_V_out_write);
    img_2_cols_V_c_U->if_dout(img_2_cols_V_c_dout);
    img_2_cols_V_c_U->if_empty_n(img_2_cols_V_c_empty_n);
    img_2_cols_V_c_U->if_read(CvtColor_1_U0_p_src_cols_V_read);
    img_3_rows_V_c_U = new fifo_w32_d6_A("img_3_rows_V_c_U");
    img_3_rows_V_c_U->clk(ap_clk);
    img_3_rows_V_c_U->reset(ap_rst_n_inv);
    img_3_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_3_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_3_rows_V_c_U->if_din(Block_Mat_exit49_pro_U0_img_3_rows_V_out_din);
    img_3_rows_V_c_U->if_full_n(img_3_rows_V_c_full_n);
    img_3_rows_V_c_U->if_write(Block_Mat_exit49_pro_U0_img_3_rows_V_out_write);
    img_3_rows_V_c_U->if_dout(img_3_rows_V_c_dout);
    img_3_rows_V_c_U->if_empty_n(img_3_rows_V_c_empty_n);
    img_3_rows_V_c_U->if_read(Mat2AXIvideo_U0_img_rows_V_read);
    img_3_cols_V_c_U = new fifo_w32_d6_A("img_3_cols_V_c_U");
    img_3_cols_V_c_U->clk(ap_clk);
    img_3_cols_V_c_U->reset(ap_rst_n_inv);
    img_3_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_3_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_3_cols_V_c_U->if_din(Block_Mat_exit49_pro_U0_img_3_cols_V_out_din);
    img_3_cols_V_c_U->if_full_n(img_3_cols_V_c_full_n);
    img_3_cols_V_c_U->if_write(Block_Mat_exit49_pro_U0_img_3_cols_V_out_write);
    img_3_cols_V_c_U->if_dout(img_3_cols_V_c_dout);
    img_3_cols_V_c_U->if_empty_n(img_3_cols_V_c_empty_n);
    img_3_cols_V_c_U->if_read(Mat2AXIvideo_U0_img_cols_V_read);
    img_0_data_stream_0_U = new fifo_w8_d2_A("img_0_data_stream_0_U");
    img_0_data_stream_0_U->clk(ap_clk);
    img_0_data_stream_0_U->reset(ap_rst_n_inv);
    img_0_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    img_0_data_stream_0_U->if_full_n(img_0_data_stream_0_full_n);
    img_0_data_stream_0_U->if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    img_0_data_stream_0_U->if_dout(img_0_data_stream_0_dout);
    img_0_data_stream_0_U->if_empty_n(img_0_data_stream_0_empty_n);
    img_0_data_stream_0_U->if_read(CvtColor_U0_p_src_data_stream_0_V_read);
    img_0_data_stream_1_U = new fifo_w8_d2_A("img_0_data_stream_1_U");
    img_0_data_stream_1_U->clk(ap_clk);
    img_0_data_stream_1_U->reset(ap_rst_n_inv);
    img_0_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    img_0_data_stream_1_U->if_full_n(img_0_data_stream_1_full_n);
    img_0_data_stream_1_U->if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    img_0_data_stream_1_U->if_dout(img_0_data_stream_1_dout);
    img_0_data_stream_1_U->if_empty_n(img_0_data_stream_1_empty_n);
    img_0_data_stream_1_U->if_read(CvtColor_U0_p_src_data_stream_1_V_read);
    img_0_data_stream_2_U = new fifo_w8_d2_A("img_0_data_stream_2_U");
    img_0_data_stream_2_U->clk(ap_clk);
    img_0_data_stream_2_U->reset(ap_rst_n_inv);
    img_0_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    img_0_data_stream_2_U->if_full_n(img_0_data_stream_2_full_n);
    img_0_data_stream_2_U->if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    img_0_data_stream_2_U->if_dout(img_0_data_stream_2_dout);
    img_0_data_stream_2_U->if_empty_n(img_0_data_stream_2_empty_n);
    img_0_data_stream_2_U->if_read(CvtColor_U0_p_src_data_stream_2_V_read);
    img_0_rows_V_c22_U = new fifo_w32_d2_A("img_0_rows_V_c22_U");
    img_0_rows_V_c22_U->clk(ap_clk);
    img_0_rows_V_c22_U->reset(ap_rst_n_inv);
    img_0_rows_V_c22_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_c22_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_c22_U->if_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    img_0_rows_V_c22_U->if_full_n(img_0_rows_V_c22_full_n);
    img_0_rows_V_c22_U->if_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    img_0_rows_V_c22_U->if_dout(img_0_rows_V_c22_dout);
    img_0_rows_V_c22_U->if_empty_n(img_0_rows_V_c22_empty_n);
    img_0_rows_V_c22_U->if_read(CvtColor_U0_p_src_rows_V_read);
    img_0_cols_V_c23_U = new fifo_w32_d2_A("img_0_cols_V_c23_U");
    img_0_cols_V_c23_U->clk(ap_clk);
    img_0_cols_V_c23_U->reset(ap_rst_n_inv);
    img_0_cols_V_c23_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_c23_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_c23_U->if_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    img_0_cols_V_c23_U->if_full_n(img_0_cols_V_c23_full_n);
    img_0_cols_V_c23_U->if_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    img_0_cols_V_c23_U->if_dout(img_0_cols_V_c23_dout);
    img_0_cols_V_c23_U->if_empty_n(img_0_cols_V_c23_empty_n);
    img_0_cols_V_c23_U->if_read(CvtColor_U0_p_src_cols_V_read);
    img_1_data_stream_0_U = new fifo_w8_d2_A("img_1_data_stream_0_U");
    img_1_data_stream_0_U->clk(ap_clk);
    img_1_data_stream_0_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_din(CvtColor_U0_p_dst_data_stream_V_din);
    img_1_data_stream_0_U->if_full_n(img_1_data_stream_0_full_n);
    img_1_data_stream_0_U->if_write(CvtColor_U0_p_dst_data_stream_V_write);
    img_1_data_stream_0_U->if_dout(img_1_data_stream_0_dout);
    img_1_data_stream_0_U->if_empty_n(img_1_data_stream_0_empty_n);
    img_1_data_stream_0_U->if_read(Threshold_U0_p_src_data_stream_V_read);
    img_2_data_stream_0_U = new fifo_w8_d2_A("img_2_data_stream_0_U");
    img_2_data_stream_0_U->clk(ap_clk);
    img_2_data_stream_0_U->reset(ap_rst_n_inv);
    img_2_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_2_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_2_data_stream_0_U->if_din(Threshold_U0_p_dst_data_stream_V_din);
    img_2_data_stream_0_U->if_full_n(img_2_data_stream_0_full_n);
    img_2_data_stream_0_U->if_write(Threshold_U0_p_dst_data_stream_V_write);
    img_2_data_stream_0_U->if_dout(img_2_data_stream_0_dout);
    img_2_data_stream_0_U->if_empty_n(img_2_data_stream_0_empty_n);
    img_2_data_stream_0_U->if_read(CvtColor_1_U0_p_src_data_stream_V_read);
    img_3_data_stream_0_U = new fifo_w8_d2_A("img_3_data_stream_0_U");
    img_3_data_stream_0_U->clk(ap_clk);
    img_3_data_stream_0_U->reset(ap_rst_n_inv);
    img_3_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_3_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_3_data_stream_0_U->if_din(CvtColor_1_U0_p_dst_data_stream_0_V_din);
    img_3_data_stream_0_U->if_full_n(img_3_data_stream_0_full_n);
    img_3_data_stream_0_U->if_write(CvtColor_1_U0_p_dst_data_stream_0_V_write);
    img_3_data_stream_0_U->if_dout(img_3_data_stream_0_dout);
    img_3_data_stream_0_U->if_empty_n(img_3_data_stream_0_empty_n);
    img_3_data_stream_0_U->if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    img_3_data_stream_1_U = new fifo_w8_d2_A("img_3_data_stream_1_U");
    img_3_data_stream_1_U->clk(ap_clk);
    img_3_data_stream_1_U->reset(ap_rst_n_inv);
    img_3_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_3_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_3_data_stream_1_U->if_din(CvtColor_1_U0_p_dst_data_stream_1_V_din);
    img_3_data_stream_1_U->if_full_n(img_3_data_stream_1_full_n);
    img_3_data_stream_1_U->if_write(CvtColor_1_U0_p_dst_data_stream_1_V_write);
    img_3_data_stream_1_U->if_dout(img_3_data_stream_1_dout);
    img_3_data_stream_1_U->if_empty_n(img_3_data_stream_1_empty_n);
    img_3_data_stream_1_U->if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    img_3_data_stream_2_U = new fifo_w8_d2_A("img_3_data_stream_2_U");
    img_3_data_stream_2_U->clk(ap_clk);
    img_3_data_stream_2_U->reset(ap_rst_n_inv);
    img_3_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_3_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_3_data_stream_2_U->if_din(CvtColor_1_U0_p_dst_data_stream_2_V_din);
    img_3_data_stream_2_U->if_full_n(img_3_data_stream_2_full_n);
    img_3_data_stream_2_U->if_write(CvtColor_1_U0_p_dst_data_stream_2_V_write);
    img_3_data_stream_2_U->if_dout(img_3_data_stream_2_dout);
    img_3_data_stream_2_U->if_empty_n(img_3_data_stream_2_empty_n);
    img_3_data_stream_2_U->if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    start_for_Threshomb6_U = new start_for_Threshomb6("start_for_Threshomb6_U");
    start_for_Threshomb6_U->clk(ap_clk);
    start_for_Threshomb6_U->reset(ap_rst_n_inv);
    start_for_Threshomb6_U->if_read_ce(ap_var_for_const0);
    start_for_Threshomb6_U->if_write_ce(ap_var_for_const0);
    start_for_Threshomb6_U->if_din(start_for_Threshold_U0_din);
    start_for_Threshomb6_U->if_full_n(start_for_Threshold_U0_full_n);
    start_for_Threshomb6_U->if_write(Block_Mat_exit49_pro_U0_start_write);
    start_for_Threshomb6_U->if_dout(start_for_Threshold_U0_dout);
    start_for_Threshomb6_U->if_empty_n(start_for_Threshold_U0_empty_n);
    start_for_Threshomb6_U->if_read(Threshold_U0_ap_ready);
    start_for_CvtColoncg_U = new start_for_CvtColoncg("start_for_CvtColoncg_U");
    start_for_CvtColoncg_U->clk(ap_clk);
    start_for_CvtColoncg_U->reset(ap_rst_n_inv);
    start_for_CvtColoncg_U->if_read_ce(ap_var_for_const0);
    start_for_CvtColoncg_U->if_write_ce(ap_var_for_const0);
    start_for_CvtColoncg_U->if_din(start_for_CvtColor_1_U0_din);
    start_for_CvtColoncg_U->if_full_n(start_for_CvtColor_1_U0_full_n);
    start_for_CvtColoncg_U->if_write(Block_Mat_exit49_pro_U0_start_write);
    start_for_CvtColoncg_U->if_dout(start_for_CvtColor_1_U0_dout);
    start_for_CvtColoncg_U->if_empty_n(start_for_CvtColor_1_U0_empty_n);
    start_for_CvtColoncg_U->if_read(CvtColor_1_U0_ap_ready);
    start_for_Mat2AXIocq_U = new start_for_Mat2AXIocq("start_for_Mat2AXIocq_U");
    start_for_Mat2AXIocq_U->clk(ap_clk);
    start_for_Mat2AXIocq_U->reset(ap_rst_n_inv);
    start_for_Mat2AXIocq_U->if_read_ce(ap_var_for_const0);
    start_for_Mat2AXIocq_U->if_write_ce(ap_var_for_const0);
    start_for_Mat2AXIocq_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXIocq_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXIocq_U->if_write(Block_Mat_exit49_pro_U0_start_write);
    start_for_Mat2AXIocq_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXIocq_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXIocq_U->if_read(Mat2AXIvideo_U0_ap_ready);
    start_for_CvtColopcA_U = new start_for_CvtColopcA("start_for_CvtColopcA_U");
    start_for_CvtColopcA_U->clk(ap_clk);
    start_for_CvtColopcA_U->reset(ap_rst_n_inv);
    start_for_CvtColopcA_U->if_read_ce(ap_var_for_const0);
    start_for_CvtColopcA_U->if_write_ce(ap_var_for_const0);
    start_for_CvtColopcA_U->if_din(start_for_CvtColor_U0_din);
    start_for_CvtColopcA_U->if_full_n(start_for_CvtColor_U0_full_n);
    start_for_CvtColopcA_U->if_write(AXIvideo2Mat_U0_start_write);
    start_for_CvtColopcA_U->if_dout(start_for_CvtColor_U0_dout);
    start_for_CvtColopcA_U->if_empty_n(start_for_CvtColor_U0_empty_n);
    start_for_CvtColopcA_U->if_read(CvtColor_U0_ap_ready);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);

    SC_METHOD(thread_Block_Mat_exit49_pro_U0_ap_continue);

    SC_METHOD(thread_Block_Mat_exit49_pro_U0_ap_start);

    SC_METHOD(thread_Block_Mat_exit49_pro_U0_start_full_n);
    sensitive << ( start_for_Threshold_U0_full_n );
    sensitive << ( start_for_CvtColor_1_U0_full_n );
    sensitive << ( start_for_Mat2AXIvideo_U0_full_n );

    SC_METHOD(thread_CvtColor_1_U0_ap_continue);

    SC_METHOD(thread_CvtColor_1_U0_ap_start);
    sensitive << ( start_for_CvtColor_1_U0_empty_n );

    SC_METHOD(thread_CvtColor_1_U0_start_full_n);

    SC_METHOD(thread_CvtColor_1_U0_start_write);

    SC_METHOD(thread_CvtColor_U0_ap_continue);

    SC_METHOD(thread_CvtColor_U0_ap_start);
    sensitive << ( start_for_CvtColor_U0_empty_n );

    SC_METHOD(thread_CvtColor_U0_start_full_n);

    SC_METHOD(thread_CvtColor_U0_start_write);

    SC_METHOD(thread_INPUT_STREAM_TREADY);
    sensitive << ( AXIvideo2Mat_U0_INPUT_STREAM_TREADY );

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_OUTPUT_STREAM_TDATA);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA );

    SC_METHOD(thread_OUTPUT_STREAM_TDEST);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST );

    SC_METHOD(thread_OUTPUT_STREAM_TID);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TID );

    SC_METHOD(thread_OUTPUT_STREAM_TKEEP);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP );

    SC_METHOD(thread_OUTPUT_STREAM_TLAST);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST );

    SC_METHOD(thread_OUTPUT_STREAM_TSTRB);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB );

    SC_METHOD(thread_OUTPUT_STREAM_TUSER);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER );

    SC_METHOD(thread_OUTPUT_STREAM_TVALID);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID );

    SC_METHOD(thread_Threshold_U0_ap_continue);

    SC_METHOD(thread_Threshold_U0_ap_start);
    sensitive << ( start_for_Threshold_U0_empty_n );

    SC_METHOD(thread_Threshold_U0_start_full_n);

    SC_METHOD(thread_Threshold_U0_start_write);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_start_for_CvtColor_1_U0_din);

    SC_METHOD(thread_start_for_CvtColor_U0_din);

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_METHOD(thread_start_for_Threshold_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ov5640_otsu_threshold_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, INPUT_STREAM_TDATA, "(port)INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, INPUT_STREAM_TKEEP, "(port)INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, INPUT_STREAM_TSTRB, "(port)INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, INPUT_STREAM_TUSER, "(port)INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, INPUT_STREAM_TLAST, "(port)INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, INPUT_STREAM_TID, "(port)INPUT_STREAM_TID");
    sc_trace(mVcdFile, INPUT_STREAM_TDEST, "(port)INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA, "(port)OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, OUTPUT_STREAM_TKEEP, "(port)OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, OUTPUT_STREAM_TSTRB, "(port)OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, OUTPUT_STREAM_TUSER, "(port)OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, OUTPUT_STREAM_TLAST, "(port)OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TID, "(port)OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDEST, "(port)OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID, "(port)INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY, "(port)INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, OUTPUT_STREAM_TVALID, "(port)OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY, "(port)OUTPUT_STREAM_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, rows, "rows");
    sc_trace(mVcdFile, cols, "cols");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_ap_start, "Block_Mat_exit49_pro_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_start_full_n, "Block_Mat_exit49_pro_U0_start_full_n");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_ap_done, "Block_Mat_exit49_pro_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_ap_continue, "Block_Mat_exit49_pro_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_ap_idle, "Block_Mat_exit49_pro_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_ap_ready, "Block_Mat_exit49_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_start_out, "Block_Mat_exit49_pro_U0_start_out");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_start_write, "Block_Mat_exit49_pro_U0_start_write");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_0_rows_V_out_din, "Block_Mat_exit49_pro_U0_img_0_rows_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_0_rows_V_out_write, "Block_Mat_exit49_pro_U0_img_0_rows_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_0_cols_V_out_din, "Block_Mat_exit49_pro_U0_img_0_cols_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_0_cols_V_out_write, "Block_Mat_exit49_pro_U0_img_0_cols_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_1_rows_V_out_din, "Block_Mat_exit49_pro_U0_img_1_rows_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_1_rows_V_out_write, "Block_Mat_exit49_pro_U0_img_1_rows_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_1_cols_V_out_din, "Block_Mat_exit49_pro_U0_img_1_cols_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_1_cols_V_out_write, "Block_Mat_exit49_pro_U0_img_1_cols_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_2_rows_V_out_din, "Block_Mat_exit49_pro_U0_img_2_rows_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_2_rows_V_out_write, "Block_Mat_exit49_pro_U0_img_2_rows_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_2_cols_V_out_din, "Block_Mat_exit49_pro_U0_img_2_cols_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_2_cols_V_out_write, "Block_Mat_exit49_pro_U0_img_2_cols_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_3_rows_V_out_din, "Block_Mat_exit49_pro_U0_img_3_rows_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_3_rows_V_out_write, "Block_Mat_exit49_pro_U0_img_3_rows_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_3_cols_V_out_din, "Block_Mat_exit49_pro_U0_img_3_cols_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit49_pro_U0_img_3_cols_V_out_write, "Block_Mat_exit49_pro_U0_img_3_cols_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_out, "AXIvideo2Mat_U0_start_out");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_INPUT_STREAM_TREADY, "AXIvideo2Mat_U0_INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_read, "AXIvideo2Mat_U0_img_rows_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_read, "AXIvideo2Mat_U0_img_cols_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_din, "AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_write, "AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_din, "AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_write, "AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_din, "AXIvideo2Mat_U0_img_data_stream_2_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_write, "AXIvideo2Mat_U0_img_data_stream_2_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_din, "AXIvideo2Mat_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_write, "AXIvideo2Mat_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_din, "AXIvideo2Mat_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_write, "AXIvideo2Mat_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, CvtColor_U0_ap_start, "CvtColor_U0_ap_start");
    sc_trace(mVcdFile, CvtColor_U0_ap_done, "CvtColor_U0_ap_done");
    sc_trace(mVcdFile, CvtColor_U0_ap_continue, "CvtColor_U0_ap_continue");
    sc_trace(mVcdFile, CvtColor_U0_ap_idle, "CvtColor_U0_ap_idle");
    sc_trace(mVcdFile, CvtColor_U0_ap_ready, "CvtColor_U0_ap_ready");
    sc_trace(mVcdFile, CvtColor_U0_p_src_rows_V_read, "CvtColor_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_cols_V_read, "CvtColor_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_data_stream_0_V_read, "CvtColor_U0_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_data_stream_1_V_read, "CvtColor_U0_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_data_stream_2_V_read, "CvtColor_U0_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_V_din, "CvtColor_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_V_write, "CvtColor_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Threshold_U0_ap_start, "Threshold_U0_ap_start");
    sc_trace(mVcdFile, Threshold_U0_ap_done, "Threshold_U0_ap_done");
    sc_trace(mVcdFile, Threshold_U0_ap_continue, "Threshold_U0_ap_continue");
    sc_trace(mVcdFile, Threshold_U0_ap_idle, "Threshold_U0_ap_idle");
    sc_trace(mVcdFile, Threshold_U0_ap_ready, "Threshold_U0_ap_ready");
    sc_trace(mVcdFile, Threshold_U0_p_src_rows_V_read, "Threshold_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, Threshold_U0_p_src_cols_V_read, "Threshold_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, Threshold_U0_p_src_data_stream_V_read, "Threshold_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, Threshold_U0_p_dst_data_stream_V_din, "Threshold_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, Threshold_U0_p_dst_data_stream_V_write, "Threshold_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_start, "CvtColor_1_U0_ap_start");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_done, "CvtColor_1_U0_ap_done");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_continue, "CvtColor_1_U0_ap_continue");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_idle, "CvtColor_1_U0_ap_idle");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_ready, "CvtColor_1_U0_ap_ready");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_rows_V_read, "CvtColor_1_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_cols_V_read, "CvtColor_1_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_data_stream_V_read, "CvtColor_1_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_0_V_din, "CvtColor_1_U0_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_0_V_write, "CvtColor_1_U0_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_1_V_din, "CvtColor_1_U0_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_1_V_write, "CvtColor_1_U0_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_2_V_din, "CvtColor_1_U0_p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_2_V_write, "CvtColor_1_U0_p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_rows_V_read, "Mat2AXIvideo_U0_img_rows_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_cols_V_read, "Mat2AXIvideo_U0_img_cols_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_0_V_read, "Mat2AXIvideo_U0_img_data_stream_0_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_1_V_read, "Mat2AXIvideo_U0_img_data_stream_1_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_2_V_read, "Mat2AXIvideo_U0_img_data_stream_2_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA, "Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID, "Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP, "Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB, "Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER, "Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST, "Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TID, "Mat2AXIvideo_U0_OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST, "Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, img_0_rows_V_c_full_n, "img_0_rows_V_c_full_n");
    sc_trace(mVcdFile, img_0_rows_V_c_dout, "img_0_rows_V_c_dout");
    sc_trace(mVcdFile, img_0_rows_V_c_empty_n, "img_0_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_c_full_n, "img_0_cols_V_c_full_n");
    sc_trace(mVcdFile, img_0_cols_V_c_dout, "img_0_cols_V_c_dout");
    sc_trace(mVcdFile, img_0_cols_V_c_empty_n, "img_0_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_1_rows_V_c_full_n, "img_1_rows_V_c_full_n");
    sc_trace(mVcdFile, img_1_rows_V_c_dout, "img_1_rows_V_c_dout");
    sc_trace(mVcdFile, img_1_rows_V_c_empty_n, "img_1_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_1_cols_V_c_full_n, "img_1_cols_V_c_full_n");
    sc_trace(mVcdFile, img_1_cols_V_c_dout, "img_1_cols_V_c_dout");
    sc_trace(mVcdFile, img_1_cols_V_c_empty_n, "img_1_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_2_rows_V_c_full_n, "img_2_rows_V_c_full_n");
    sc_trace(mVcdFile, img_2_rows_V_c_dout, "img_2_rows_V_c_dout");
    sc_trace(mVcdFile, img_2_rows_V_c_empty_n, "img_2_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_2_cols_V_c_full_n, "img_2_cols_V_c_full_n");
    sc_trace(mVcdFile, img_2_cols_V_c_dout, "img_2_cols_V_c_dout");
    sc_trace(mVcdFile, img_2_cols_V_c_empty_n, "img_2_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_3_rows_V_c_full_n, "img_3_rows_V_c_full_n");
    sc_trace(mVcdFile, img_3_rows_V_c_dout, "img_3_rows_V_c_dout");
    sc_trace(mVcdFile, img_3_rows_V_c_empty_n, "img_3_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_3_cols_V_c_full_n, "img_3_cols_V_c_full_n");
    sc_trace(mVcdFile, img_3_cols_V_c_dout, "img_3_cols_V_c_dout");
    sc_trace(mVcdFile, img_3_cols_V_c_empty_n, "img_3_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_full_n, "img_0_data_stream_0_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_dout, "img_0_data_stream_0_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_empty_n, "img_0_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_1_full_n, "img_0_data_stream_1_full_n");
    sc_trace(mVcdFile, img_0_data_stream_1_dout, "img_0_data_stream_1_dout");
    sc_trace(mVcdFile, img_0_data_stream_1_empty_n, "img_0_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_2_full_n, "img_0_data_stream_2_full_n");
    sc_trace(mVcdFile, img_0_data_stream_2_dout, "img_0_data_stream_2_dout");
    sc_trace(mVcdFile, img_0_data_stream_2_empty_n, "img_0_data_stream_2_empty_n");
    sc_trace(mVcdFile, img_0_rows_V_c22_full_n, "img_0_rows_V_c22_full_n");
    sc_trace(mVcdFile, img_0_rows_V_c22_dout, "img_0_rows_V_c22_dout");
    sc_trace(mVcdFile, img_0_rows_V_c22_empty_n, "img_0_rows_V_c22_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_c23_full_n, "img_0_cols_V_c23_full_n");
    sc_trace(mVcdFile, img_0_cols_V_c23_dout, "img_0_cols_V_c23_dout");
    sc_trace(mVcdFile, img_0_cols_V_c23_empty_n, "img_0_cols_V_c23_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_full_n, "img_1_data_stream_0_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_dout, "img_1_data_stream_0_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_empty_n, "img_1_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_2_data_stream_0_full_n, "img_2_data_stream_0_full_n");
    sc_trace(mVcdFile, img_2_data_stream_0_dout, "img_2_data_stream_0_dout");
    sc_trace(mVcdFile, img_2_data_stream_0_empty_n, "img_2_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_3_data_stream_0_full_n, "img_3_data_stream_0_full_n");
    sc_trace(mVcdFile, img_3_data_stream_0_dout, "img_3_data_stream_0_dout");
    sc_trace(mVcdFile, img_3_data_stream_0_empty_n, "img_3_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_3_data_stream_1_full_n, "img_3_data_stream_1_full_n");
    sc_trace(mVcdFile, img_3_data_stream_1_dout, "img_3_data_stream_1_dout");
    sc_trace(mVcdFile, img_3_data_stream_1_empty_n, "img_3_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_3_data_stream_2_full_n, "img_3_data_stream_2_full_n");
    sc_trace(mVcdFile, img_3_data_stream_2_dout, "img_3_data_stream_2_dout");
    sc_trace(mVcdFile, img_3_data_stream_2_empty_n, "img_3_data_stream_2_empty_n");
    sc_trace(mVcdFile, start_for_Threshold_U0_din, "start_for_Threshold_U0_din");
    sc_trace(mVcdFile, start_for_Threshold_U0_full_n, "start_for_Threshold_U0_full_n");
    sc_trace(mVcdFile, start_for_Threshold_U0_dout, "start_for_Threshold_U0_dout");
    sc_trace(mVcdFile, start_for_Threshold_U0_empty_n, "start_for_Threshold_U0_empty_n");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_din, "start_for_CvtColor_1_U0_din");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_full_n, "start_for_CvtColor_1_U0_full_n");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_dout, "start_for_CvtColor_1_U0_dout");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_empty_n, "start_for_CvtColor_1_U0_empty_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, start_for_CvtColor_U0_din, "start_for_CvtColor_U0_din");
    sc_trace(mVcdFile, start_for_CvtColor_U0_full_n, "start_for_CvtColor_U0_full_n");
    sc_trace(mVcdFile, start_for_CvtColor_U0_dout, "start_for_CvtColor_U0_dout");
    sc_trace(mVcdFile, start_for_CvtColor_U0_empty_n, "start_for_CvtColor_U0_empty_n");
    sc_trace(mVcdFile, CvtColor_U0_start_full_n, "CvtColor_U0_start_full_n");
    sc_trace(mVcdFile, CvtColor_U0_start_write, "CvtColor_U0_start_write");
    sc_trace(mVcdFile, Threshold_U0_start_full_n, "Threshold_U0_start_full_n");
    sc_trace(mVcdFile, Threshold_U0_start_write, "Threshold_U0_start_write");
    sc_trace(mVcdFile, CvtColor_1_U0_start_full_n, "CvtColor_1_U0_start_full_n");
    sc_trace(mVcdFile, CvtColor_1_U0_start_write, "CvtColor_1_U0_start_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("ov5640_otsu_threshold.hdltvin.dat");
    mHdltvoutHandle.open("ov5640_otsu_threshold.hdltvout.dat");
}

ov5640_otsu_threshold::~ov5640_otsu_threshold() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete ov5640_otsu_threshold_AXILiteS_s_axi_U;
    delete Block_Mat_exit49_pro_U0;
    delete AXIvideo2Mat_U0;
    delete CvtColor_U0;
    delete Threshold_U0;
    delete CvtColor_1_U0;
    delete Mat2AXIvideo_U0;
    delete img_0_rows_V_c_U;
    delete img_0_cols_V_c_U;
    delete img_1_rows_V_c_U;
    delete img_1_cols_V_c_U;
    delete img_2_rows_V_c_U;
    delete img_2_cols_V_c_U;
    delete img_3_rows_V_c_U;
    delete img_3_cols_V_c_U;
    delete img_0_data_stream_0_U;
    delete img_0_data_stream_1_U;
    delete img_0_data_stream_2_U;
    delete img_0_rows_V_c22_U;
    delete img_0_cols_V_c23_U;
    delete img_1_data_stream_0_U;
    delete img_2_data_stream_0_U;
    delete img_3_data_stream_0_U;
    delete img_3_data_stream_1_U;
    delete img_3_data_stream_2_U;
    delete start_for_Threshomb6_U;
    delete start_for_CvtColoncg_U;
    delete start_for_Mat2AXIocq_U;
    delete start_for_CvtColopcA_U;
}

void ov5640_otsu_threshold::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_Block_Mat_exit49_pro_U0_ap_continue() {
    Block_Mat_exit49_pro_U0_ap_continue = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_Block_Mat_exit49_pro_U0_ap_start() {
    Block_Mat_exit49_pro_U0_ap_start = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_Block_Mat_exit49_pro_U0_start_full_n() {
    Block_Mat_exit49_pro_U0_start_full_n = (start_for_Threshold_U0_full_n.read() & start_for_CvtColor_1_U0_full_n.read() & start_for_Mat2AXIvideo_U0_full_n.read());
}

void ov5640_otsu_threshold::thread_CvtColor_1_U0_ap_continue() {
    CvtColor_1_U0_ap_continue = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_CvtColor_1_U0_ap_start() {
    CvtColor_1_U0_ap_start = start_for_CvtColor_1_U0_empty_n.read();
}

void ov5640_otsu_threshold::thread_CvtColor_1_U0_start_full_n() {
    CvtColor_1_U0_start_full_n = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_CvtColor_1_U0_start_write() {
    CvtColor_1_U0_start_write = ap_const_logic_0;
}

void ov5640_otsu_threshold::thread_CvtColor_U0_ap_continue() {
    CvtColor_U0_ap_continue = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_CvtColor_U0_ap_start() {
    CvtColor_U0_ap_start = start_for_CvtColor_U0_empty_n.read();
}

void ov5640_otsu_threshold::thread_CvtColor_U0_start_full_n() {
    CvtColor_U0_start_full_n = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_CvtColor_U0_start_write() {
    CvtColor_U0_start_write = ap_const_logic_0;
}

void ov5640_otsu_threshold::thread_INPUT_STREAM_TREADY() {
    INPUT_STREAM_TREADY = AXIvideo2Mat_U0_INPUT_STREAM_TREADY.read();
}

void ov5640_otsu_threshold::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void ov5640_otsu_threshold::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void ov5640_otsu_threshold::thread_OUTPUT_STREAM_TDATA() {
    OUTPUT_STREAM_TDATA = Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA.read();
}

void ov5640_otsu_threshold::thread_OUTPUT_STREAM_TDEST() {
    OUTPUT_STREAM_TDEST = Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST.read();
}

void ov5640_otsu_threshold::thread_OUTPUT_STREAM_TID() {
    OUTPUT_STREAM_TID = Mat2AXIvideo_U0_OUTPUT_STREAM_TID.read();
}

void ov5640_otsu_threshold::thread_OUTPUT_STREAM_TKEEP() {
    OUTPUT_STREAM_TKEEP = Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP.read();
}

void ov5640_otsu_threshold::thread_OUTPUT_STREAM_TLAST() {
    OUTPUT_STREAM_TLAST = Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST.read();
}

void ov5640_otsu_threshold::thread_OUTPUT_STREAM_TSTRB() {
    OUTPUT_STREAM_TSTRB = Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB.read();
}

void ov5640_otsu_threshold::thread_OUTPUT_STREAM_TUSER() {
    OUTPUT_STREAM_TUSER = Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER.read();
}

void ov5640_otsu_threshold::thread_OUTPUT_STREAM_TVALID() {
    OUTPUT_STREAM_TVALID = Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID.read();
}

void ov5640_otsu_threshold::thread_Threshold_U0_ap_continue() {
    Threshold_U0_ap_continue = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_Threshold_U0_ap_start() {
    Threshold_U0_ap_start = start_for_Threshold_U0_empty_n.read();
}

void ov5640_otsu_threshold::thread_Threshold_U0_start_full_n() {
    Threshold_U0_start_full_n = ap_const_logic_1;
}

void ov5640_otsu_threshold::thread_Threshold_U0_start_write() {
    Threshold_U0_start_write = ap_const_logic_0;
}

void ov5640_otsu_threshold::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void ov5640_otsu_threshold::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void ov5640_otsu_threshold::thread_start_for_CvtColor_1_U0_din() {
    start_for_CvtColor_1_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_otsu_threshold::thread_start_for_CvtColor_U0_din() {
    start_for_CvtColor_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_otsu_threshold::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_otsu_threshold::thread_start_for_Threshold_U0_din() {
    start_for_Threshold_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_otsu_threshold::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDATA\" :  \"" << INPUT_STREAM_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TKEEP\" :  \"" << INPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TSTRB\" :  \"" << INPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TUSER\" :  \"" << INPUT_STREAM_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TLAST\" :  \"" << INPUT_STREAM_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TID\" :  \"" << INPUT_STREAM_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDEST\" :  \"" << INPUT_STREAM_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDATA\" :  \"" << OUTPUT_STREAM_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TKEEP\" :  \"" << OUTPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TSTRB\" :  \"" << OUTPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TUSER\" :  \"" << OUTPUT_STREAM_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TLAST\" :  \"" << OUTPUT_STREAM_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TID\" :  \"" << OUTPUT_STREAM_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDEST\" :  \"" << OUTPUT_STREAM_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TVALID\" :  \"" << INPUT_STREAM_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"INPUT_STREAM_TREADY\" :  \"" << INPUT_STREAM_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TVALID\" :  \"" << OUTPUT_STREAM_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"OUTPUT_STREAM_TREADY\" :  \"" << OUTPUT_STREAM_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

