// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state7 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_read;
input  [31:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond460_i_reg_1386;
reg   [0:0] exitcond460_i_reg_1386_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_1395;
reg   [0:0] or_cond_i_i_reg_1395_pp0_iter1_reg;
reg   [0:0] icmp_reg_1351;
reg   [0:0] tmp_5_reg_1342;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] or_cond_i_reg_1418;
reg   [0:0] or_cond_i_reg_1418_pp0_iter2_reg;
reg   [31:0] t_V_2_reg_277;
wire   [31:0] tmp_s_fu_288_p2;
reg   [31:0] tmp_s_reg_1299;
wire   [31:0] tmp_1_fu_294_p2;
reg   [31:0] tmp_1_reg_1304;
wire   [31:0] p_neg465_i_fu_300_p2;
reg   [31:0] p_neg465_i_reg_1309;
wire   [31:0] tmp_2_fu_306_p2;
reg   [31:0] tmp_2_reg_1316;
wire   [31:0] tmp_4_fu_318_p2;
reg   [31:0] tmp_4_reg_1321;
wire   [31:0] tmp_8_fu_330_p2;
reg   [31:0] tmp_8_reg_1328;
wire   [0:0] exitcond461_i_fu_336_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] i_V_fu_341_p2;
reg   [31:0] i_V_reg_1337;
wire   [0:0] tmp_5_fu_347_p2;
wire   [0:0] tmp_70_0_not_fu_352_p2;
reg   [0:0] tmp_70_0_not_reg_1346;
wire   [0:0] icmp_fu_368_p2;
wire   [0:0] tmp_12_fu_374_p2;
reg   [0:0] tmp_12_reg_1356;
wire   [0:0] tmp_114_1_fu_380_p2;
reg   [0:0] tmp_114_1_reg_1360;
wire   [0:0] tmp_13_fu_386_p2;
reg   [0:0] tmp_13_reg_1364;
wire   [1:0] tmp_23_fu_601_p1;
reg   [1:0] tmp_23_reg_1371;
wire   [1:0] tmp_24_fu_626_p1;
reg   [1:0] tmp_24_reg_1376;
wire   [1:0] tmp_32_fu_651_p1;
reg   [1:0] tmp_32_reg_1381;
wire   [0:0] exitcond460_i_fu_655_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
reg    ap_predicate_op156_read_state5;
reg    ap_predicate_op167_read_state5;
reg    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] j_V_fu_660_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_707_p2;
wire   [31:0] x_fu_771_p3;
reg   [31:0] x_reg_1399;
wire   [0:0] brmerge_fu_784_p2;
reg   [0:0] brmerge_reg_1404;
reg   [0:0] brmerge_reg_1404_pp0_iter1_reg;
wire   [1:0] tmp_37_fu_789_p1;
reg   [1:0] tmp_37_reg_1411;
reg   [1:0] tmp_37_reg_1411_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_793_p2;
reg   [0:0] or_cond_i_reg_1418_pp0_iter1_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_1422;
reg   [10:0] k_buf_0_val_4_addr_reg_1428;
reg   [10:0] k_buf_0_val_5_addr_reg_1434;
wire   [7:0] src_kernel_win_0_va_7_fu_941_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_1440;
wire   [10:0] tmp21_fu_1045_p2;
reg   [10:0] tmp21_reg_1446;
wire   [9:0] tmp23_fu_1051_p2;
reg   [9:0] tmp23_reg_1451;
wire   [7:0] tmp24_fu_1057_p2;
reg   [7:0] tmp24_reg_1456;
wire   [7:0] tmp26_fu_1063_p2;
reg   [7:0] tmp26_reg_1461;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_condition_pp0_exit_iter2_state5;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [10:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [10:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [10:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [31:0] t_V_reg_266;
wire    ap_CS_fsm_state7;
wire   [63:0] tmp_25_fu_798_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_128;
wire   [7:0] src_kernel_win_0_va_6_fu_923_p3;
reg   [7:0] src_kernel_win_0_va_1_fu_132;
reg   [7:0] src_kernel_win_0_va_2_fu_136;
reg   [7:0] src_kernel_win_0_va_3_fu_140;
reg   [7:0] src_kernel_win_0_va_4_fu_144;
wire   [7:0] src_kernel_win_0_va_8_fu_959_p3;
reg   [7:0] src_kernel_win_0_va_5_fu_148;
reg   [7:0] right_border_buf_0_s_fu_152;
wire   [7:0] col_buf_0_val_0_0_fu_833_p3;
reg   [7:0] right_border_buf_0_1_fu_156;
reg   [7:0] right_border_buf_0_2_fu_160;
reg   [7:0] right_border_buf_0_3_fu_164;
wire   [7:0] col_buf_0_val_1_0_fu_851_p3;
reg   [7:0] right_border_buf_0_4_fu_168;
reg   [7:0] right_border_buf_0_5_fu_172;
wire   [7:0] col_buf_0_val_2_0_fu_869_p3;
wire   [31:0] tmp_3_fu_312_p2;
wire   [31:0] tmp_7_fu_324_p2;
wire   [30:0] tmp_10_fu_358_p4;
wire   [31:0] tmp_14_fu_391_p2;
wire   [0:0] tmp_15_fu_397_p3;
wire   [0:0] tmp_16_fu_411_p2;
wire   [0:0] rev_fu_405_p2;
wire   [0:0] tmp_17_fu_422_p3;
wire   [31:0] p_assign_7_fu_430_p2;
wire   [31:0] p_p2_i497_i_fu_436_p3;
wire   [31:0] p_assign_6_1_fu_454_p2;
wire   [0:0] tmp_19_fu_460_p3;
wire   [0:0] tmp_140_1_fu_474_p2;
wire   [0:0] rev1_fu_468_p2;
wire   [0:0] tmp_20_fu_485_p3;
wire   [31:0] p_assign_7_1_fu_493_p2;
wire   [31:0] p_p2_i497_i_1_fu_499_p3;
wire   [31:0] p_assign_6_2_fu_517_p2;
wire   [0:0] tmp_21_fu_523_p3;
wire   [0:0] tmp_140_2_fu_537_p2;
wire   [0:0] rev2_fu_531_p2;
wire   [0:0] tmp_22_fu_548_p3;
wire   [31:0] p_assign_7_2_fu_556_p2;
wire   [31:0] p_p2_i497_i_2_fu_562_p3;
wire   [0:0] tmp_18_fu_444_p2;
wire   [31:0] p_assign_8_fu_449_p2;
wire   [0:0] or_cond_i496_i_fu_416_p2;
wire   [31:0] p_p2_i497_i_p_assign_8_fu_580_p3;
wire   [31:0] y_fu_588_p3;
wire   [31:0] row_assign_9_fu_596_p2;
wire   [0:0] tmp_149_1_fu_507_p2;
wire   [31:0] p_assign_8_1_fu_512_p2;
wire   [0:0] or_cond_i496_i_1_fu_479_p2;
wire   [31:0] p_p2_i497_i_1_p_assig_fu_605_p3;
wire   [31:0] y_1_fu_613_p3;
wire   [31:0] row_assign_9_1_fu_621_p2;
wire   [0:0] tmp_149_2_fu_570_p2;
wire   [31:0] p_assign_8_2_fu_575_p2;
wire   [0:0] or_cond_i496_i_2_fu_542_p2;
wire   [31:0] p_p2_i497_i_2_p_assig_fu_630_p3;
wire   [31:0] y_2_fu_638_p3;
wire   [31:0] row_assign_9_2_fu_646_p2;
wire   [30:0] tmp_33_fu_666_p4;
wire   [31:0] ImagLoc_x_fu_682_p2;
wire   [0:0] tmp_34_fu_688_p3;
wire   [0:0] tmp_9_fu_702_p2;
wire   [0:0] rev3_fu_696_p2;
wire   [0:0] tmp_35_fu_713_p3;
wire   [31:0] p_assign_1_fu_721_p2;
wire   [31:0] p_p2_i_i_fu_727_p3;
wire   [31:0] p_assign_2_fu_740_p2;
wire   [0:0] tmp_9_not_fu_753_p2;
wire   [0:0] tmp_11_fu_735_p2;
wire   [0:0] sel_tmp7_fu_759_p2;
wire   [0:0] sel_tmp8_fu_765_p2;
wire   [31:0] p_assign_3_fu_745_p3;
wire   [31:0] col_assign_1_fu_779_p2;
wire   [0:0] icmp1_fu_676_p2;
wire   [7:0] tmp_26_fu_822_p5;
wire   [7:0] tmp_27_fu_840_p5;
wire   [7:0] tmp_28_fu_858_p5;
wire   [7:0] tmp_29_fu_912_p5;
wire   [7:0] tmp_30_fu_930_p5;
wire   [7:0] tmp_31_fu_948_p5;
wire   [8:0] tmp_156_0_2_cast_fu_979_p1;
wire   [8:0] r_V_0_cast_fu_975_p1;
wire  signed [8:0] sum_V_0_2_fu_983_p2;
wire   [8:0] p_shl_fu_993_p3;
wire   [9:0] p_shl_cast_fu_1001_p1;
wire  signed [9:0] r_V_10_1_fu_1005_p2;
wire   [8:0] r_V_2_cast_fu_1023_p1;
wire  signed [8:0] r_V_10_2_fu_1027_p2;
wire  signed [10:0] tmp_156_2_cast_fu_1033_p1;
wire  signed [10:0] tmp_156_1_cast_fu_1011_p1;
wire   [9:0] tmp_156_2_2_cast_cas_fu_1041_p1;
wire  signed [9:0] sum_V_0_2_cast_cast_fu_989_p1;
wire   [7:0] tmp_41_fu_1019_p1;
wire   [7:0] tmp_40_fu_1015_p1;
wire   [7:0] tmp_43_fu_1037_p1;
wire   [8:0] r_V_10_1_2_fu_1108_p3;
wire   [10:0] tmp_156_1_cast_63_fu_1115_p1;
wire  signed [10:0] tmp23_cast_fu_1124_p1;
wire   [10:0] tmp22_fu_1127_p2;
wire   [10:0] p_Val2_s_fu_1133_p2;
wire   [7:0] tmp_42_fu_1119_p2;
wire   [7:0] tmp25_fu_1146_p2;
wire   [0:0] p_Result_s_fu_1138_p3;
wire   [2:0] tmp_36_fu_1156_p4;
wire   [0:0] not_i_i_fu_1172_p2;
wire   [0:0] tmp_i_i_fu_1166_p2;
wire   [0:0] overflow_fu_1178_p2;
wire   [0:0] tmp_1_i_i_fu_1192_p2;
wire   [7:0] p_mux_i_i_cast_fu_1184_p3;
wire   [7:0] p_Val2_1_fu_1151_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_131;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_enable_operation_147;
reg    ap_enable_state5_pp0_iter2_stage0;
reg    ap_predicate_op161_store_state5;
reg    ap_enable_operation_161;
reg    ap_predicate_op168_store_state5;
reg    ap_enable_operation_168;
reg    ap_enable_operation_133;
reg    ap_enable_operation_150;
reg    ap_predicate_op159_store_state5;
reg    ap_enable_operation_159;
reg    ap_predicate_op166_store_state5;
reg    ap_enable_operation_166;
reg    ap_predicate_op135_load_state4;
reg    ap_enable_operation_135;
reg    ap_predicate_op153_load_state5;
reg    ap_enable_operation_153;
reg    ap_predicate_op157_store_state5;
reg    ap_enable_operation_157;
reg    ap_predicate_op165_store_state5;
reg    ap_enable_operation_165;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_926;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

ov5640_sobel_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ov5640_sobel_mux_hbi_U37(
    .din0(right_border_buf_0_s_fu_152),
    .din1(right_border_buf_0_1_fu_156),
    .din2(8'd0),
    .din3(tmp_37_reg_1411_pp0_iter1_reg),
    .dout(tmp_26_fu_822_p5)
);

ov5640_sobel_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ov5640_sobel_mux_hbi_U38(
    .din0(right_border_buf_0_3_fu_164),
    .din1(right_border_buf_0_4_fu_168),
    .din2(8'd0),
    .din3(tmp_37_reg_1411_pp0_iter1_reg),
    .dout(tmp_27_fu_840_p5)
);

ov5640_sobel_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ov5640_sobel_mux_hbi_U39(
    .din0(right_border_buf_0_5_fu_172),
    .din1(right_border_buf_0_2_fu_160),
    .din2(8'd0),
    .din3(tmp_37_reg_1411_pp0_iter1_reg),
    .dout(tmp_28_fu_858_p5)
);

ov5640_sobel_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ov5640_sobel_mux_hbi_U40(
    .din0(col_buf_0_val_0_0_fu_833_p3),
    .din1(col_buf_0_val_1_0_fu_851_p3),
    .din2(col_buf_0_val_2_0_fu_869_p3),
    .din3(tmp_23_reg_1371),
    .dout(tmp_29_fu_912_p5)
);

ov5640_sobel_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ov5640_sobel_mux_hbi_U41(
    .din0(col_buf_0_val_0_0_fu_833_p3),
    .din1(col_buf_0_val_1_0_fu_851_p3),
    .din2(col_buf_0_val_2_0_fu_869_p3),
    .din3(tmp_24_reg_1376),
    .dout(tmp_30_fu_930_p5)
);

ov5640_sobel_mux_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ov5640_sobel_mux_hbi_U42(
    .din0(col_buf_0_val_0_0_fu_833_p3),
    .din1(col_buf_0_val_1_0_fu_851_p3),
    .din2(col_buf_0_val_2_0_fu_869_p3),
    .din3(tmp_32_reg_1381),
    .dout(tmp_31_fu_948_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond460_i_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond461_i_fu_336_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((((exitcond461_i_fu_336_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_condition_pp0_exit_iter2_state5) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter2_state5) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((exitcond461_i_fu_336_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_fu_655_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_277 <= j_V_fu_660_p2;
    end else if (((exitcond461_i_fu_336_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_2_reg_277 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_266 <= i_V_reg_1337;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_266 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1404 <= brmerge_fu_784_p2;
        or_cond_i_i_reg_1395 <= or_cond_i_i_fu_707_p2;
        or_cond_i_reg_1418 <= or_cond_i_fu_793_p2;
        tmp_37_reg_1411 <= tmp_37_fu_789_p1;
        x_reg_1399 <= x_fu_771_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1404_pp0_iter1_reg <= brmerge_reg_1404;
        exitcond460_i_reg_1386 <= exitcond460_i_fu_655_p2;
        exitcond460_i_reg_1386_pp0_iter1_reg <= exitcond460_i_reg_1386;
        or_cond_i_i_reg_1395_pp0_iter1_reg <= or_cond_i_i_reg_1395;
        or_cond_i_reg_1418_pp0_iter1_reg <= or_cond_i_reg_1418;
        tmp_37_reg_1411_pp0_iter1_reg <= tmp_37_reg_1411;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1337 <= i_V_fu_341_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_336_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_1351 <= icmp_fu_368_p2;
        tmp_114_1_reg_1360 <= tmp_114_1_fu_380_p2;
        tmp_12_reg_1356 <= tmp_12_fu_374_p2;
        tmp_13_reg_1364 <= tmp_13_fu_386_p2;
        tmp_23_reg_1371 <= tmp_23_fu_601_p1;
        tmp_24_reg_1376 <= tmp_24_fu_626_p1;
        tmp_32_reg_1381 <= tmp_32_fu_651_p1;
        tmp_5_reg_1342 <= tmp_5_fu_347_p2;
        tmp_70_0_not_reg_1346 <= tmp_70_0_not_fu_352_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1386 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_addr_reg_1422 <= tmp_25_fu_798_p1;
        k_buf_0_val_4_addr_reg_1428 <= tmp_25_fu_798_p1;
        k_buf_0_val_5_addr_reg_1434 <= tmp_25_fu_798_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        or_cond_i_reg_1418_pp0_iter2_reg <= or_cond_i_reg_1418_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_neg465_i_reg_1309 <= p_neg465_i_fu_300_p2;
        tmp_1_reg_1304 <= tmp_1_fu_294_p2;
        tmp_2_reg_1316 <= tmp_2_fu_306_p2;
        tmp_4_reg_1321[31 : 1] <= tmp_4_fu_318_p2[31 : 1];
        tmp_8_reg_1328[31 : 1] <= tmp_8_fu_330_p2[31 : 1];
        tmp_s_reg_1299 <= tmp_s_fu_288_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_1_fu_156 <= right_border_buf_0_s_fu_152;
        right_border_buf_0_2_fu_160 <= right_border_buf_0_5_fu_172;
        right_border_buf_0_3_fu_164 <= col_buf_0_val_1_0_fu_851_p3;
        right_border_buf_0_4_fu_168 <= right_border_buf_0_3_fu_164;
        right_border_buf_0_5_fu_172 <= col_buf_0_val_2_0_fu_869_p3;
        right_border_buf_0_s_fu_152 <= col_buf_0_val_0_0_fu_833_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_132 <= src_kernel_win_0_va_fu_128;
        src_kernel_win_0_va_2_fu_136 <= src_kernel_win_0_va_7_fu_941_p3;
        src_kernel_win_0_va_3_fu_140 <= src_kernel_win_0_va_2_fu_136;
        src_kernel_win_0_va_4_fu_144 <= src_kernel_win_0_va_8_fu_959_p3;
        src_kernel_win_0_va_5_fu_148 <= src_kernel_win_0_va_4_fu_144;
        src_kernel_win_0_va_fu_128 <= src_kernel_win_0_va_6_fu_923_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_7_reg_1440 <= src_kernel_win_0_va_7_fu_941_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1418_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp21_reg_1446 <= tmp21_fu_1045_p2;
        tmp23_reg_1451 <= tmp23_fu_1051_p2;
        tmp24_reg_1456 <= tmp24_fu_1057_p2;
        tmp26_reg_1461 <= tmp26_fu_1063_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond461_i_fu_336_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond461_i_fu_336_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_12_reg_1356 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_12_reg_1356 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_114_1_reg_1360 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_926)) begin
        if (((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_114_1_reg_1360 == 1'd1) & (icmp_reg_1351 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_114_1_reg_1360 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_12_reg_1356 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_926)) begin
        if (((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_12_reg_1356 == 1'd1) & (icmp_reg_1351 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_12_reg_1356 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1418_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1418_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op167_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op156_read_state5 == 1'b1)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond461_i_fu_336_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_682_p2 = ($signed(32'd4294967295) + $signed(t_V_2_reg_277));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((or_cond_i_reg_1418_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op167_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op156_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((or_cond_i_reg_1418_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op167_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op156_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((or_cond_i_reg_1418_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op167_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op156_read_state5 == 1'b1)))));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op167_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op156_read_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter3 = ((or_cond_i_reg_1418_pp0_iter2_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_926 = ((or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_enable_operation_131 = (exitcond460_i_reg_1386 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_133 = (exitcond460_i_reg_1386 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_135 = (ap_predicate_op135_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_147 = (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_150 = (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_153 = (ap_predicate_op153_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_157 = (ap_predicate_op157_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_159 = (ap_predicate_op159_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_161 = (ap_predicate_op161_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_165 = (ap_predicate_op165_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_166 = (ap_predicate_op166_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_168 = (ap_predicate_op168_store_state5 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op135_load_state4 = ((brmerge_reg_1404 == 1'd1) & (exitcond460_i_reg_1386 == 1'd0));
end

always @ (*) begin
    ap_predicate_op153_load_state5 = ((brmerge_reg_1404_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op156_read_state5 = ((or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op157_store_state5 = ((tmp_12_reg_1356 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op159_store_state5 = ((tmp_114_1_reg_1360 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op161_store_state5 = ((tmp_12_reg_1356 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (icmp_reg_1351 == 1'd0) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op165_store_state5 = ((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op166_store_state5 = ((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op167_read_state5 = ((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op168_store_state5 = ((tmp_5_reg_1342 == 1'd1) & (icmp_reg_1351 == 1'd1) & (or_cond_i_i_reg_1395_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1386_pp0_iter1_reg == 1'd0));
end

assign brmerge_fu_784_p2 = (tmp_9_fu_702_p2 | tmp_70_0_not_reg_1346);

assign col_assign_1_fu_779_p2 = (tmp_2_reg_1316 - x_fu_771_p3);

assign col_buf_0_val_0_0_fu_833_p3 = ((brmerge_reg_1404_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_26_fu_822_p5);

assign col_buf_0_val_1_0_fu_851_p3 = ((brmerge_reg_1404_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_27_fu_840_p5);

assign col_buf_0_val_2_0_fu_869_p3 = ((brmerge_reg_1404_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_28_fu_858_p5);

assign exitcond460_i_fu_655_p2 = ((t_V_2_reg_277 == tmp_s_reg_1299) ? 1'b1 : 1'b0);

assign exitcond461_i_fu_336_p2 = ((t_V_reg_266 == tmp_1_reg_1304) ? 1'b1 : 1'b0);

assign i_V_fu_341_p2 = (t_V_reg_266 + 32'd1);

assign icmp1_fu_676_p2 = ((tmp_33_fu_666_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_fu_368_p2 = ((tmp_10_fu_358_p4 != 31'd0) ? 1'b1 : 1'b0);

assign j_V_fu_660_p2 = (t_V_2_reg_277 + 32'd1);

assign k_buf_0_val_3_address0 = tmp_25_fu_798_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1422;

assign k_buf_0_val_4_address0 = tmp_25_fu_798_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_1428;

assign k_buf_0_val_5_address0 = tmp_25_fu_798_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_1434;

assign not_i_i_fu_1172_p2 = ((tmp_36_fu_1156_p4 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i496_i_1_fu_479_p2 = (tmp_140_1_fu_474_p2 & rev1_fu_468_p2);

assign or_cond_i496_i_2_fu_542_p2 = (tmp_140_2_fu_537_p2 & rev2_fu_531_p2);

assign or_cond_i496_i_fu_416_p2 = (tmp_16_fu_411_p2 & rev_fu_405_p2);

assign or_cond_i_fu_793_p2 = (icmp_reg_1351 & icmp1_fu_676_p2);

assign or_cond_i_i_fu_707_p2 = (tmp_9_fu_702_p2 & rev3_fu_696_p2);

assign overflow_fu_1178_p2 = (tmp_i_i_fu_1166_p2 & not_i_i_fu_1172_p2);

assign p_Result_s_fu_1138_p3 = p_Val2_s_fu_1133_p2[32'd10];

assign p_Val2_1_fu_1151_p2 = (tmp24_reg_1456 + tmp25_fu_1146_p2);

assign p_Val2_s_fu_1133_p2 = (tmp21_reg_1446 + tmp22_fu_1127_p2);

assign p_assign_1_fu_721_p2 = (32'd1 - t_V_2_reg_277);

assign p_assign_2_fu_740_p2 = (tmp_8_reg_1328 - p_p2_i_i_fu_727_p3);

assign p_assign_3_fu_745_p3 = ((or_cond_i_i_fu_707_p2[0:0] === 1'b1) ? ImagLoc_x_fu_682_p2 : p_assign_2_fu_740_p2);

assign p_assign_6_1_fu_454_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_266));

assign p_assign_6_2_fu_517_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_266));

assign p_assign_7_1_fu_493_p2 = (32'd2 - t_V_reg_266);

assign p_assign_7_2_fu_556_p2 = (32'd3 - t_V_reg_266);

assign p_assign_7_fu_430_p2 = (32'd1 - t_V_reg_266);

assign p_assign_8_1_fu_512_p2 = (tmp_4_reg_1321 - p_p2_i497_i_1_fu_499_p3);

assign p_assign_8_2_fu_575_p2 = (tmp_4_reg_1321 - p_p2_i497_i_2_fu_562_p3);

assign p_assign_8_fu_449_p2 = (tmp_4_reg_1321 - p_p2_i497_i_fu_436_p3);

assign p_dst_data_stream_V_din = ((tmp_1_i_i_fu_1192_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1184_p3 : p_Val2_1_fu_1151_p2);

assign p_mux_i_i_cast_fu_1184_p3 = ((tmp_i_i_fu_1166_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_neg465_i_fu_300_p2 = ($signed(32'd4294967295) + $signed(p_src_rows_V_read));

assign p_p2_i497_i_1_fu_499_p3 = ((tmp_20_fu_485_p3[0:0] === 1'b1) ? p_assign_7_1_fu_493_p2 : p_assign_6_1_fu_454_p2);

assign p_p2_i497_i_1_p_assig_fu_605_p3 = ((tmp_149_1_fu_507_p2[0:0] === 1'b1) ? p_p2_i497_i_1_fu_499_p3 : p_assign_8_1_fu_512_p2);

assign p_p2_i497_i_2_fu_562_p3 = ((tmp_22_fu_548_p3[0:0] === 1'b1) ? p_assign_7_2_fu_556_p2 : p_assign_6_2_fu_517_p2);

assign p_p2_i497_i_2_p_assig_fu_630_p3 = ((tmp_149_2_fu_570_p2[0:0] === 1'b1) ? p_p2_i497_i_2_fu_562_p3 : p_assign_8_2_fu_575_p2);

assign p_p2_i497_i_fu_436_p3 = ((tmp_17_fu_422_p3[0:0] === 1'b1) ? p_assign_7_fu_430_p2 : tmp_14_fu_391_p2);

assign p_p2_i497_i_p_assign_8_fu_580_p3 = ((tmp_18_fu_444_p2[0:0] === 1'b1) ? p_p2_i497_i_fu_436_p3 : p_assign_8_fu_449_p2);

assign p_p2_i_i_fu_727_p3 = ((tmp_35_fu_713_p3[0:0] === 1'b1) ? p_assign_1_fu_721_p2 : ImagLoc_x_fu_682_p2);

assign p_shl_cast_fu_1001_p1 = p_shl_fu_993_p3;

assign p_shl_fu_993_p3 = {{src_kernel_win_0_va_3_fu_140}, {1'd0}};

assign r_V_0_cast_fu_975_p1 = src_kernel_win_0_va_5_fu_148;

assign r_V_10_1_2_fu_1108_p3 = {{src_kernel_win_0_va_7_reg_1440}, {1'd0}};

assign r_V_10_1_fu_1005_p2 = (10'd0 - p_shl_cast_fu_1001_p1);

assign r_V_10_2_fu_1027_p2 = (9'd0 - r_V_2_cast_fu_1023_p1);

assign r_V_2_cast_fu_1023_p1 = src_kernel_win_0_va_1_fu_132;

assign rev1_fu_468_p2 = (tmp_19_fu_460_p3 ^ 1'd1);

assign rev2_fu_531_p2 = (tmp_21_fu_523_p3 ^ 1'd1);

assign rev3_fu_696_p2 = (tmp_34_fu_688_p3 ^ 1'd1);

assign rev_fu_405_p2 = (tmp_15_fu_397_p3 ^ 1'd1);

assign row_assign_9_1_fu_621_p2 = (p_neg465_i_reg_1309 - y_1_fu_613_p3);

assign row_assign_9_2_fu_646_p2 = (p_neg465_i_reg_1309 - y_2_fu_638_p3);

assign row_assign_9_fu_596_p2 = (p_neg465_i_reg_1309 - y_fu_588_p3);

assign sel_tmp7_fu_759_p2 = (tmp_9_not_fu_753_p2 | tmp_34_fu_688_p3);

assign sel_tmp8_fu_765_p2 = (tmp_11_fu_735_p2 & sel_tmp7_fu_759_p2);

assign src_kernel_win_0_va_6_fu_923_p3 = ((tmp_13_reg_1364[0:0] === 1'b1) ? tmp_29_fu_912_p5 : col_buf_0_val_0_0_fu_833_p3);

assign src_kernel_win_0_va_7_fu_941_p3 = ((tmp_13_reg_1364[0:0] === 1'b1) ? tmp_30_fu_930_p5 : col_buf_0_val_1_0_fu_851_p3);

assign src_kernel_win_0_va_8_fu_959_p3 = ((tmp_13_reg_1364[0:0] === 1'b1) ? tmp_31_fu_948_p5 : col_buf_0_val_2_0_fu_869_p3);

assign sum_V_0_2_cast_cast_fu_989_p1 = sum_V_0_2_fu_983_p2;

assign sum_V_0_2_fu_983_p2 = (tmp_156_0_2_cast_fu_979_p1 - r_V_0_cast_fu_975_p1);

assign tmp21_fu_1045_p2 = ($signed(tmp_156_2_cast_fu_1033_p1) + $signed(tmp_156_1_cast_fu_1011_p1));

assign tmp22_fu_1127_p2 = ($signed(tmp_156_1_cast_63_fu_1115_p1) + $signed(tmp23_cast_fu_1124_p1));

assign tmp23_cast_fu_1124_p1 = $signed(tmp23_reg_1451);

assign tmp23_fu_1051_p2 = ($signed(tmp_156_2_2_cast_cas_fu_1041_p1) + $signed(sum_V_0_2_cast_cast_fu_989_p1));

assign tmp24_fu_1057_p2 = (tmp_41_fu_1019_p1 + tmp_40_fu_1015_p1);

assign tmp25_fu_1146_p2 = (tmp_42_fu_1119_p2 + tmp26_reg_1461);

assign tmp26_fu_1063_p2 = (src_kernel_win_0_va_6_fu_923_p3 + tmp_43_fu_1037_p1);

assign tmp_10_fu_358_p4 = {{t_V_reg_266[31:1]}};

assign tmp_114_1_fu_380_p2 = ((t_V_reg_266 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_735_p2 = (($signed(p_p2_i_i_fu_727_p3) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_12_fu_374_p2 = ((t_V_reg_266 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_13_fu_386_p2 = ((t_V_reg_266 > p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_140_1_fu_474_p2 = (($signed(p_assign_6_1_fu_454_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_140_2_fu_537_p2 = (($signed(p_assign_6_2_fu_517_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_149_1_fu_507_p2 = (($signed(p_p2_i497_i_1_fu_499_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_149_2_fu_570_p2 = (($signed(p_p2_i497_i_2_fu_562_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_14_fu_391_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_266));

assign tmp_156_0_2_cast_fu_979_p1 = src_kernel_win_0_va_8_fu_959_p3;

assign tmp_156_1_cast_63_fu_1115_p1 = r_V_10_1_2_fu_1108_p3;

assign tmp_156_1_cast_fu_1011_p1 = r_V_10_1_fu_1005_p2;

assign tmp_156_2_2_cast_cas_fu_1041_p1 = src_kernel_win_0_va_6_fu_923_p3;

assign tmp_156_2_cast_fu_1033_p1 = r_V_10_2_fu_1027_p2;

assign tmp_15_fu_397_p3 = tmp_14_fu_391_p2[32'd31];

assign tmp_16_fu_411_p2 = (($signed(tmp_14_fu_391_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_17_fu_422_p3 = tmp_14_fu_391_p2[32'd31];

assign tmp_18_fu_444_p2 = (($signed(p_p2_i497_i_fu_436_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_19_fu_460_p3 = p_assign_6_1_fu_454_p2[32'd31];

assign tmp_1_fu_294_p2 = (32'd2 + p_src_rows_V_read);

assign tmp_1_i_i_fu_1192_p2 = (p_Result_s_fu_1138_p3 | overflow_fu_1178_p2);

assign tmp_20_fu_485_p3 = p_assign_6_1_fu_454_p2[32'd31];

assign tmp_21_fu_523_p3 = p_assign_6_2_fu_517_p2[32'd31];

assign tmp_22_fu_548_p3 = p_assign_6_2_fu_517_p2[32'd31];

assign tmp_23_fu_601_p1 = row_assign_9_fu_596_p2[1:0];

assign tmp_24_fu_626_p1 = row_assign_9_1_fu_621_p2[1:0];

assign tmp_25_fu_798_p1 = x_reg_1399;

assign tmp_2_fu_306_p2 = (32'd3 + p_src_cols_V_read);

assign tmp_32_fu_651_p1 = row_assign_9_2_fu_646_p2[1:0];

assign tmp_33_fu_666_p4 = {{t_V_2_reg_277[31:1]}};

assign tmp_34_fu_688_p3 = ImagLoc_x_fu_682_p2[32'd31];

assign tmp_35_fu_713_p3 = ImagLoc_x_fu_682_p2[32'd31];

assign tmp_36_fu_1156_p4 = {{p_Val2_s_fu_1133_p2[10:8]}};

assign tmp_37_fu_789_p1 = col_assign_1_fu_779_p2[1:0];

assign tmp_3_fu_312_p2 = p_src_rows_V_read << 32'd1;

assign tmp_40_fu_1015_p1 = sum_V_0_2_fu_983_p2[7:0];

assign tmp_41_fu_1019_p1 = r_V_10_1_fu_1005_p2[7:0];

assign tmp_42_fu_1119_p2 = src_kernel_win_0_va_7_reg_1440 << 8'd1;

assign tmp_43_fu_1037_p1 = r_V_10_2_fu_1027_p2[7:0];

assign tmp_4_fu_318_p2 = (32'd2 + tmp_3_fu_312_p2);

assign tmp_5_fu_347_p2 = ((t_V_reg_266 < p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_70_0_not_fu_352_p2 = (tmp_5_fu_347_p2 ^ 1'd1);

assign tmp_7_fu_324_p2 = p_src_cols_V_read << 32'd1;

assign tmp_8_fu_330_p2 = ($signed(32'd4294967294) + $signed(tmp_7_fu_324_p2));

assign tmp_9_fu_702_p2 = (($signed(ImagLoc_x_fu_682_p2) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_9_not_fu_753_p2 = (tmp_9_fu_702_p2 ^ 1'd1);

assign tmp_i_i_fu_1166_p2 = (p_Result_s_fu_1138_p3 ^ 1'd1);

assign tmp_s_fu_288_p2 = (32'd2 + p_src_cols_V_read);

assign x_fu_771_p3 = ((sel_tmp8_fu_765_p2[0:0] === 1'b1) ? p_p2_i_i_fu_727_p3 : p_assign_3_fu_745_p3);

assign y_1_fu_613_p3 = ((or_cond_i496_i_1_fu_479_p2[0:0] === 1'b1) ? p_assign_6_1_fu_454_p2 : p_p2_i497_i_1_p_assig_fu_605_p3);

assign y_2_fu_638_p3 = ((or_cond_i496_i_2_fu_542_p2[0:0] === 1'b1) ? p_assign_6_2_fu_517_p2 : p_p2_i497_i_2_p_assig_fu_630_p3);

assign y_fu_588_p3 = ((or_cond_i496_i_fu_416_p2[0:0] === 1'b1) ? tmp_14_fu_391_p2 : p_p2_i497_i_p_assign_8_fu_580_p3);

always @ (posedge ap_clk) begin
    tmp_4_reg_1321[0] <= 1'b0;
    tmp_8_reg_1328[0] <= 1'b0;
end

endmodule //Filter2D
