// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="qrc_decoder,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2018_3}" *)

module qrc_decoder (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pdata_address0,
        pdata_ce0,
        pdata_we0,
        pdata_d0,
        pdata_q0,
        pdata_address1,
        pdata_ce1,
        pdata_we1,
        pdata_d1,
        pdata_q1,
        dataout
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] pdata_address0;
output   pdata_ce0;
output   pdata_we0;
output  [7:0] pdata_d0;
input  [7:0] pdata_q0;
output  [8:0] pdata_address1;
output   pdata_ce1;
output   pdata_we1;
output  [7:0] pdata_d1;
input  [7:0] pdata_q1;
input  [7:0] dataout;

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign pdata_address0 = 9'd0;

assign pdata_address1 = 9'd0;

assign pdata_ce0 = 1'b0;

assign pdata_ce1 = 1'b0;

assign pdata_d0 = 8'd0;

assign pdata_d1 = 8'd0;

assign pdata_we0 = 1'b0;

assign pdata_we1 = 1'b0;

endmodule //qrc_decoder
