// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "qrc_decoder.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic qrc_decoder::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<9> qrc_decoder::ap_const_lv9_0 = "000000000";
const sc_logic qrc_decoder::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> qrc_decoder::ap_const_lv8_0 = "00000000";

qrc_decoder::qrc_decoder(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_pdata_address0);

    SC_METHOD(thread_pdata_address1);

    SC_METHOD(thread_pdata_ce0);

    SC_METHOD(thread_pdata_ce1);

    SC_METHOD(thread_pdata_d0);

    SC_METHOD(thread_pdata_d1);

    SC_METHOD(thread_pdata_we0);

    SC_METHOD(thread_pdata_we1);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "qrc_decoder_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, pdata_address0, "(port)pdata_address0");
    sc_trace(mVcdFile, pdata_ce0, "(port)pdata_ce0");
    sc_trace(mVcdFile, pdata_we0, "(port)pdata_we0");
    sc_trace(mVcdFile, pdata_d0, "(port)pdata_d0");
    sc_trace(mVcdFile, pdata_q0, "(port)pdata_q0");
    sc_trace(mVcdFile, pdata_address1, "(port)pdata_address1");
    sc_trace(mVcdFile, pdata_ce1, "(port)pdata_ce1");
    sc_trace(mVcdFile, pdata_we1, "(port)pdata_we1");
    sc_trace(mVcdFile, pdata_d1, "(port)pdata_d1");
    sc_trace(mVcdFile, pdata_q1, "(port)pdata_q1");
    sc_trace(mVcdFile, dataout, "(port)dataout");
#endif

    }
    mHdltvinHandle.open("qrc_decoder.hdltvin.dat");
    mHdltvoutHandle.open("qrc_decoder.hdltvout.dat");
}

qrc_decoder::~qrc_decoder() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void qrc_decoder::thread_ap_done() {
    ap_done = ap_start.read();
}

void qrc_decoder::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void qrc_decoder::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void qrc_decoder::thread_pdata_address0() {
    pdata_address0 = ap_const_lv9_0;
}

void qrc_decoder::thread_pdata_address1() {
    pdata_address1 = ap_const_lv9_0;
}

void qrc_decoder::thread_pdata_ce0() {
    pdata_ce0 = ap_const_logic_0;
}

void qrc_decoder::thread_pdata_ce1() {
    pdata_ce1 = ap_const_logic_0;
}

void qrc_decoder::thread_pdata_d0() {
    pdata_d0 = ap_const_lv8_0;
}

void qrc_decoder::thread_pdata_d1() {
    pdata_d1 = ap_const_lv8_0;
}

void qrc_decoder::thread_pdata_we0() {
    pdata_we0 = ap_const_logic_0;
}

void qrc_decoder::thread_pdata_we1() {
    pdata_we1 = ap_const_logic_0;
}

void qrc_decoder::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pdata_address0\" :  \"" << pdata_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pdata_ce0\" :  \"" << pdata_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pdata_we0\" :  \"" << pdata_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pdata_d0\" :  \"" << pdata_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pdata_q0\" :  \"" << pdata_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pdata_address1\" :  \"" << pdata_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pdata_ce1\" :  \"" << pdata_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pdata_we1\" :  \"" << pdata_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pdata_d1\" :  \"" << pdata_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pdata_q1\" :  \"" << pdata_q1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dataout\" :  \"" << dataout.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

