// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _qrc_decoder_HH_
#define _qrc_decoder_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct qrc_decoder : public sc_module {
    // Port declarations 15
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<9> > pdata_address0;
    sc_out< sc_logic > pdata_ce0;
    sc_out< sc_logic > pdata_we0;
    sc_out< sc_lv<8> > pdata_d0;
    sc_in< sc_lv<8> > pdata_q0;
    sc_out< sc_lv<9> > pdata_address1;
    sc_out< sc_logic > pdata_ce1;
    sc_out< sc_logic > pdata_we1;
    sc_out< sc_lv<8> > pdata_d1;
    sc_in< sc_lv<8> > pdata_q1;
    sc_in< sc_lv<8> > dataout;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    qrc_decoder(sc_module_name name);
    SC_HAS_PROCESS(qrc_decoder);

    ~qrc_decoder();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_const_lv8_0;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_pdata_address0();
    void thread_pdata_address1();
    void thread_pdata_ce0();
    void thread_pdata_ce1();
    void thread_pdata_d0();
    void thread_pdata_d1();
    void thread_pdata_we0();
    void thread_pdata_we1();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
